### ISSUE TITLE
Highly dynamic data storage

### ISSUE THREAD

**Issue by nothingismagick** [iotaledger/stronghold.rs#26]
## Description
A storage type that does not track changes.

## Motivation
We need to have a way to store highly dynamic data without bloating the stronghold file.

## Requirements

1. define type at creation
2. not bloat the changelog (and explode the size of the stronghold)
3. be tuned for performance

## Open questions (optional)
Datastructure: trie could be nice, but also a minor engineering feat

@bernardoaraujor

**Comment by bernardoaraujor** [comment]
From the perspective of IOTA Access, it's important to have a secure storage for Access Policies.
Since IOTA Access Servers run on constrained devices, there needs to be some upper limit to the size of the Strongheld Policies.

At the moment I can't think of any criteria under which Policies would be dumped when limit is reached.
Assume time: when reach storage size limit of Strongheld Policies, erase oldest Policy.

A simple approach for implementation would be:
- Strongheld Policies are stored in a circular buffer, which is implemented as an array of pointers to each SP. 
- For every new `store_policy` operation, increment head pointer.
- If head pointer reaches buffer size, reset head pointer.

That keeps the vault for Strongheld Policies as constant size.

**Comment by nothingismagick** [comment]
Also related to your comment @bernardoaraujor - #27

**Comment by nothingismagick** [comment]
@cvarley100 & @laumair - would love to have your feedback on this feature request as well.

**Comment by bernardoaraujor** [comment]
perhaps related to this issue: https://ferrous-systems.com/blog/lock-free-ring-buffer/

**Comment by nothingismagick** [comment]
This will resolve with the new client.
