### ISSUE TITLE
Snapshot crate won't build on esp32

### ISSUE THREAD

**Issue by nothingismagick** [iotaledger/stronghold.rs#29]
## Bug description

@wusyong has had partial success building for the esp32, with one caveat:

```
I have cross compiled stronghold to xtensa-eps32-none-elf and all engine crates can 
pass except snapshot. It has a dependency of `dir` which needs to call `libc`. 
And this is the kind of library that going to be incompatible between different targets. 
Is it possible to make this crate behind a feature?
```

@bernardoaraujor mentioned the following:
```
Also in this context, the ESP32-WROOM-32SE has an ATECC608A, which is industry standard for HW-based ECC.
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/secure_element.html
```

**Comment by bernardoaraujor** [comment]
Further reference on the `esp32-WROOM-32SE`:
- https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32se_datasheet_en.pdf

-  https://www.mouser.de/ProductDetail/Espressif-Systems/ESP32-DevKitC-32D?qs=%252BEew9%252B0nqrDsObWEpDx6YQ%3D%3D

- https://github.com/espressif/esp-idf/tree/c77c4ccf6c43ab09fd89e7c907bf5cf2a3499e3b/examples/peripherals/secure_element/atecc608_ecdsa

**Comment by bernardoaraujor** [comment]
As an alternative (in case Rust development on the ESP32 becomes too costly), there's the Coral Environment Sensor: https://coral.ai/products/environmental

It contains an ATECC608A and only costs $15.

It comes in a Raspberry Pi form factor, which means perhaps a Coral board ($130) is not necessary, while a Raspberry Pi 3/4 ($30) could do the job.

Since both boards have 64bit ARM Cortex As capable of running full Linux environments, running Rust would become less of a challenge in those environments.

Microchip's cryptoauthlib API mentioned above could be also be used in this setting to `write`, `lock` and `read` the `seed`s from the ATECC608A.

**Comment by tensor-programming** [comment]
Just an FYI, Dir was used simple for Utility functions which absolutely can be removed.  Its primarily used to locate the user's home directory so that the snapshots can be saved in a consistent area across the major operating systems.

**Comment by nothingismagick** [comment]
Bumping this issue so we can review it before the alpha release. It is also, in my opinion, something that can be expected of the consumer of the client.

**Comment by bernardoaraujor** [comment]
@wusyong could you provide the steps to reproduce the build for ESP32?

**Comment by elenaf9** [comment]
I ran into the same issue when compiling for the target `arm-unknown-linux-gnueabihf` [ref](https://github.com/iotaledger/stronghold.rs/issues/55#issuecomment-744405822) because our dependency `ring-v0.16` also depends on `libc`. In my case I was able to solve it by setting the environment variable `TARGET_CC=arm-linux-gnueabihf-gcc` for compilation, but not sure  if something similar can be applied for the `xtensa-eps32-none-elf` target.
